version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-12.26
    steps:
      - checkout

      # Stack setup
      - restore_cache:
          keys:
            - v1-stack-ghc-{{ .Branch }}-{{ checksum "stack.yaml" }}
            - v1-stack-ghc-{{ .Branch }}
            - v1-stack-ghc
      - run: stack setup
      - save_cache:
          key: v1-stack-ghc-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
      

      # Build deps
      - restore_cache:
          keys:
            - v1-stack-deps-{{ .Branch }}-{{ checksum "package.yaml" }}
            - v1-stack-deps-{{ .Branch }}
            - v1-stack-deps
      - run: stack build --only-dependencies --test
      - save_cache:
          key: v1-stack-deps-{{ .Branch }}-{{ checksum "package.yaml" }}

      # Build bin
      - restore_cache:
          keys:
            - v1-stack-bin-{{ .Branch }}-{{ checksum "package.yaml" }}
            - v1-stack-bin-{{ .Branch }}
            - v1-stack-bin
      - run: stack build
      - save_cache:
          key: v1-stack-bin-{{ .Branch }}-{{ checksum "package.yaml" }}

      # Test
      - restore_cache:
          keys:
            - v1-stack-test-{{ .Branch }}-{{ checksum "package.yaml" }}
            - v1-stack-test-{{ .Branch }}
            - v1-stack-test
      - run: stack test
      - save_cache:
          key: v1-stack-test-{{ .Branch }}-{{ checksum "package.yaml" }}
