version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-12.26
    steps:
      - checkout

      # Update stack
      - run: stack upgrade

      # Stack setup
      - restore_cache:
          keys:
            - c-{{ .Environment.CACHE_VERSION }}-stack-ghc-{{ .Branch }}-{{ checksum "stack.yaml" }}
            - c-{{ .Environment.CACHE_VERSION }}-stack-ghc-{{ .Branch }}
            - c-{{ .Environment.CACHE_VERSION }}-stack-ghc
      - run: stack setup
      - save_cache:
          key: c-{{ .Environment.CACHE_VERSION }}-stack-ghc-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
      

      # Build deps
      - restore_cache:
          keys:
            - c-{{ .Environment.CACHE_VERSION }}-stack-deps-{{ .Branch }}-{{ checksum "package.yaml" }}
            - c-{{ .Environment.CACHE_VERSION }}-stack-deps-{{ .Branch }}
            - c-{{ .Environment.CACHE_VERSION }}-stack-deps
      # We run in a single thread because otherwise it runs out of memory in CI
      - run: stack -j 1 build --only-dependencies --test
      - save_cache:
          key: c-{{ .Environment.CACHE_VERSION }}-stack-deps-{{ .Branch }}-{{ checksum "package.yaml" }}
          paths:
            - ~/.stack
            - .stack-work

      # Build bin
      - restore_cache:
          keys:
            - c-{{ .Environment.CACHE_VERSION }}-stack-bin-{{ .Branch }}-{{ checksum "package.yaml" }}
            - c-{{ .Environment.CACHE_VERSION }}-stack-bin-{{ .Branch }}
            - c-{{ .Environment.CACHE_VERSION }}-stack-bin
      - run: stack build
      - save_cache:
          key: c-{{ .Environment.CACHE_VERSION }}-stack-bin-{{ .Branch }}-{{ checksum "package.yaml" }}
          paths:
            - ~/.stack
            - .stack-work

      # Test
      - restore_cache:
          keys:
            - c-{{ .Environment.CACHE_VERSION }}-stack-test-{{ .Branch }}-{{ checksum "package.yaml" }}
            - c-{{ .Environment.CACHE_VERSION }}-stack-test-{{ .Branch }}
            - c-{{ .Environment.CACHE_VERSION }}-stack-test
      - run: stack test
      - save_cache:
          key: c-{{ .Environment.CACHE_VERSION }}-stack-test-{{ .Branch }}-{{ checksum "package.yaml" }}
          paths:
            - ~/.stack
            - .stack-work
